export default {
  login: "ragibayon",
  id: 17874721,
  node_id: "MDQ6VXNlcjE3ODc0NzIx",
  avatar_url: "https://avatars.githubusercontent.com/u/17874721?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ragibayon",
  html_url: "https://github.com/ragibayon",
  followers_url: "https://api.github.com/users/ragibayon/followers",
  following_url:
    "https://api.github.com/users/ragibayon/following{/other_user}",
  gists_url: "https://api.github.com/users/ragibayon/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ragibayon/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ragibayon/subscriptions",
  organizations_url: "https://api.github.com/users/ragibayon/orgs",
  repos_url: "https://api.github.com/users/ragibayon/repos",
  events_url: "https://api.github.com/users/ragibayon/events{/privacy}",
  received_events_url: "https://api.github.com/users/ragibayon/received_events",
  type: "User",
  site_admin: false,
  name: "Ragib Shahariar Ayon",
  company: null,
  blog: "https://www.linkedin.com/in/ragibayon",
  location: "Dhaka, Bangladesh",
  email: null,
  hireable: true,
  bio: "Data Science enthusiast!!\r\nElectronics and Telecommunication Engineer.\r\n",
  twitter_username: null,
  public_repos: 55,
  public_gists: 26,
  followers: 23,
  following: 21,
  created_at: "2016-03-16T09:08:45Z",
  updated_at: "2023-04-17T02:59:46Z",
};
